# Use following keys for type  #
#   bool    = 2                #
#   int     = 3                #
#   float   = 4                #
#   string  = 5                #

- key: effort
  type: 3
  value: 1

- key: resampling
  type: 3
  value: 4

- key: distance
  type: 4
  value: 25