# Use following keys for type  #
#   bool    = 2                #
#   int     = 3                #
#   float   = 4                #
#   string  = 5                #

- key: fail_case
  type: 3
  value: 11